### ISSUE TITLE
Support HiDPI screens

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/rasterview#11]
I have a QHD screen (2560x1440) and many users have even higher (4K and more) screen resolution.
The GUI of rasterview seems to use a hard-coded pixel count (or DPI) for menu font sizes, buttons, ... So these GUI elements get tiny on high-resolution screens.
Can this get fixed by using the actual DPI of the screen? Many GUIs, like GTK for example, do this and so one has useful GUI element sizes on any screen resolution.

**Comment by michaelrsweet** [comment]
Looks like FLTK 1.4 will end up with [HiDPI support](
http://www.fltk.org/str.php?L3320) - will probably need to wait a bit for that to become available but maybe I can host a snapshot for the snap build bot...

**Comment by michaelrsweet** [comment]
Trying this now - hopefully the snap, built against last week's FLTK 1.4 weekly snapshot, will do the trick...

**Comment by tillkamppeter** [comment]
It is working now, thank you very much.
