### ISSUE TITLE
v1.7.1: Version number is incorrect

### ISSUE THREAD

**Issue by wifiprintguy** [michaelrsweet/rasterview#14]
If you do a Get Info in the Finder on RasterView.app version 1.7.1, it says the version is 1.6. Here's from the Info.plist:

	<key>CFBundleVersion</key>
	<string>1.6</string>

	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>

	<key>NSHumanReadableCopyright</key>
	<string>Copyright © 2002-2018 by Michael R Sweet</string>

	<key>CFAppleHelpAnchor</key>
	<string>help</string>

	<key>CFBundleName</key>
	<string>RasterView</string>

	<key>CFBundlePackageType</key>
	<string>APPL</string>

	<key>CFBundleSignature</key>
	<string>CUPS</string>

	<key>CFBundleIconFile</key>
	<string>rasterview.icns</string>

	<key>CFBundleShortVersionString</key>
	<string>1.6</string>

	<key>CFBundleGetInfoString</key>
	<string>1.6, Copyright © 2002-2018 by Michael R Sweet</string>

**Comment by wifiprintguy** [comment]
I tried running rest review last night to look at some URF files and the display stayed blank. I was going to do a little more testing first but wondered if you had a similar experience running it on Big Sur.

On Jan 20, 2021, at 2:52 PM, Michael R Sweet <notifications@github.com> wrote:

﻿

D'oh! I'll probably turn the crank on RasterView to update it for Big Sur anyways, so I can do this at the same time.

**Comment by michaelrsweet** [comment]
Yeah, there are some minor issues with the FLTK UI I need to resolve... :/

**Comment by michaelrsweet** [comment]
OK, current Git sources compiled against FLTK 1.4 (also git sources) seem to work much better.
