### ISSUE TITLE
Image display too limited, cannot display A4 page in 1200 dpi

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/rasterview#16]
I am using rasterview 1.7.1 from the Snap and if I create a CUPS Raster file with 1200 dpi and A4 page size no page image appears and a pop-up message telling that the pixel dimensions exceed a limit. The header data in the pull-out part on the right is correct, but one cannot advance to the second page of the document. Probably there is a fixed-size buffer to hold the raster data which is too small for said page size and resolution and so the page does not get fully read, meaning that the next page's header is not accessible.

**Comment by michaelrsweet** [comment]
@tillkamppeter Right now there is a 256MB limit, but for 1200 DPI you'd need at least 600MB. But AFAIK no printer asks for 1200DPI raster data.

**Comment by tillkamppeter** [comment]
What about Epson inkjets (5760x1440 dpi) with a Gutenprint Printer Application which will come sooner or later?

**Comment by michaelrsweet** [comment]
@tillkamppeter Honestly, pumping full resolution data that is just going to be dithered is a waste of resources, and there are some hard memory and file format limits on client devices that will prevent them from ever utilizing them, i.e., Apple Raster doesn't support different X and Y resolutions, and iOS won't allocate huge amounts of memory to rasterize a job. I'm hoping the eventual Gutenprint printer application will simply report raster resolutions of 300/360 and 600/720 dpi, and then upsample the incoming raster data for the internal driver resolution based on print quality and other settings.

Presumably if we had a license-compatible PDF renderer (i.e. *not* Ghostscript or MuPDF) then the Gutenprint printer application could use it to render PDFs at the exact resolution needed, but given their architecture there would still be a LOT of buffering happening that could prove problematic.

Anyways, I will increase the limits to allow for up to 1440dpi CMYK on A3/Tabloid (which puts us in the 2GB range), but I'm not going to go beyond that.

**Comment by michaelrsweet** [comment]
[master b63b93c] Increase maximum bitmap size to 2GB (Issue #16)
