### ISSUE TITLE
Is Windows really supported?

### ISSUE THREAD

**Issue by deakjahn** [michaelrsweet/rasterview#17]
The repo description mentions Windows but is there any reason to think that it can be compiled and used on Windows? The source doesn't really look like it. :-)

**Comment by deakjahn** [comment]
OK, I spoke too soon, I found FTLK. I started to make it build. First observation:

https://github.com/michaelrsweet/rasterview/blob/05fe309be609a853691f237274c8fba19546ee08/RasterView.cxx#L1196

should probably be

    snprintf(s, sizeof(s), "%s - %s", VERSION, base);

**Comment by michaelrsweet** [comment]
@deakjahn No, first because the version should come last and second because "VERSION" is a defined string constant that is concatenated with the first part of the format string.

**Comment by deakjahn** [comment]
Then it's a difference in the building process. In my case, the compiler clearly complains about the missing comma. Anyway, that's least of my worries, I'm almost there, compiled, still struggling with linking. It wasn't plain sailing and requires some manual tweaking but I still have hopes. :-)

**Comment by deakjahn** [comment]
OK, success. I'll write up some details if somebody else would need it, too.

![Untitled-1](https://user-images.githubusercontent.com/2234271/172687973-68df052f-9ff1-4451-ae42-e3157c5d99e4.png)

**Comment by deakjahn** [comment]
1. Download FTLK. There's an `ide` folder with MSVC projects, build the last one. Collect the following files from the `test` and `lib` folders:

* fltk.lib
* fltkforms.lib
* fltkimages.lib
* fltkjpeg.lib
* fltkpng.lib
* fltkzlib.lib
* fl_call_main.obj

2. Copy the following packages into your RasterView source tree:

* FL from FLTK
* cups
* portable (of libportable)
* unistd (of libunistd)
* zlib (also from FLTK)

3. Modify the VERSION line mentioned above. The normal build process creates it but we're outside the normal build process now.

4. Set up your own makefile or whatever to compile. You need to compile five source files:

* main.cxx
* RasterView.cxx
* RasterDisplay.cxx
* raster.c
* error.c

5. ...and link the resulting object files plus `fl_call_main.obj` against:

* kernel32.lib
* user32.lib
* gdi32.lib
* advapi32.lib
* comdlg32.lib
* shell32.lib
* ole32.lib
* oleaut32.lib
* fltk.lib
* fltkzlib.lib
* fltkjpeg.lib
* fltkpng.lib
* fltkimages.lib

6. My compiler flags were:

* C files: /nologo /MD /FC /GS /W1 /Zi /Gm /Od /Ob2 /Gd /Oy- /Os /Zc:wchar_t /Zc:inline /D_CRT_SECURE_NO_DEPRECATE /DWIN32_LEAN_AND_MEAN /DVC_EXTRA_LEAN /DWIN32_EXTRA_LEAN /c
* C++ files: the above plus /EHsc
* linker: /nologo /incremental:no /dynamicbase:no /manifest:no /machine:X86 /safeseh /nodefaultlib:libcd /out:RasterView.exe /subsystem:windows

I won't say all of the compiler switches are required, I just started with what FTLK uses in its demo project. Also, remember to also add your includes directories to both the source package above and
the `ucrt`, `um` and `shared` folders of your Windows SDK. You cna probably use the comman dline version of any contemporary Visual Studio version.
