### ISSUE TITLE
There is still "strlcpy" in the source code of rasterview 1.5

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/rasterview#2]
When trying to compile rasterview 1.5 it chokes on "strlcpy" in raster.c.
After discovering that your intention in 1.4.1 was to replace all "strlcpy" by "strncpy" I did
perl -p -i -e 's/strlcpy/strncpy/g' *.[ch]*
and all worked perfectly. Can you fix that? Thanks.

**Comment by michaelrsweet** [comment]
Must have missed that substitution when I grabbed the latest raster code...  strncpy is not a drop-in replacement for strlcpy, but I'll do what's needed to make this compile on Linux.

(I'm also setting up a snap for this project so it will be available on Linux that way...)

**Comment by michaelrsweet** [comment]
This is fixed in TOT.
