### ISSUE TITLE
"Open" dialog filter doesn't support ".urf" file extension by default

### ISSUE THREAD

**Issue by wifiprintguy** [michaelrsweet/rasterview#3]
The "Apple Raster" format uses the .urf file extension by default when printing through an "ippserver" IPP Printer. Yet RasterView 1.5 doesn't include that extension by default in its open dialog. That extension should be added.

**Comment by michaelrsweet** [comment]
Actually I should fix ippserver to use .apple for the extension...

**Comment by wifiprintguy** [comment]
👍  Your preference

**Comment by michaelrsweet** [comment]
Pushed a change to the ippsample project: [master f9d64f9] Use .apple extension for image/urf files.
