### ISSUE TITLE
[Feature Request] Support opening of .gz compressed raster files?

### ISSUE THREAD

**Issue by KurtPfeifle** [michaelrsweet/rasterview#7]
Would it be unreasonable to ask for support of opening + viewing of such .gz-compressed raster files as are provided within the *[istopwg/ippsampe/examples/](https://github.com/istopwg/ippsample/tree/master/examples)* directory?

Currently it is required to uncompress these first before even being able to even browse and detect them from the "open file" dialog of RasterView.

**Comment by michaelrsweet** [comment]
Yes, reasonable, and should be doable. :)

**Comment by michaelrsweet** [comment]
[master f83a003] Add support for gzip'd raster files (Issue #7).
