### ISSUE TITLE
Add page navigation controls for multi-page documents

### ISSUE THREAD

**Issue by wifiprintguy** [michaelrsweet/rasterview#9]
For supporting multi-page documents such as the PWG's sample PWG Raster documents, some of which have multiple pages, it would be good to have controls that allow one to navigate the document: "next page" / "previous page", perhaps a text box showing the current page that is editable so that the user can enter a value to go directly to the page, total number of pages.

**Comment by michaelrsweet** [comment]
There was already a "next page" button, but 1.7 now includes full page navigation controls...

**Comment by wifiprintguy** [comment]
Looks good - thanks Mike!

When I look at the "sgray-8/document-letter-sgray-8-300dpi.pwg" from http://ftp.pwg.org/pub/pwg/ipp/examples/pwg-raster-samples-300dpi-20150616.zip, it still won't move to page 2, though the header reports there are 4 pages. So perhaps the document issues being reported in ippdoclint are legitimate...

**Comment by michaelrsweet** [comment]
Yeah, I need to go through the files and see what's up. And maybe do a fresh generation of the sample files using ipptransform (now that we have a standalone program that can do that... :)
